#!/usr/bin/env bash
# Bash script to install nginx on a web-server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start 
