#!/usr/bin/env bash
# configures the Nginx server with a custom header

sudo apt-get -y update
sudo apt-get -y install nginx

sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo service nginx start
