#!/usr/bin/env bash
# Displays "Best School" 10 times but displays "Hi" after the eight iteration

j=0
while (( j < 10 ));
do
    if [ $j -eq 8 ]; then
        echo "Hi";
    else
	echo "Best School";
    fi
    (( j++ ));
done
