#!/usr/bin/env bash
# Displays "Best School" 10 times but displays "Hi" after the eight iteration

j=1
while [ $j -le 10 ];
do
	echo "Best School";
	if [ $j -eq 9 ]; then
		echo "Hi";
	fi
	(( j++ ));
done
