#!/usr/bin/env bash
# configures ubuntu to deny all incoming traffic except some specific TCP ports.

# install the firewall
sudo apt -y update
sudo apt -y install ufw

# configure firewall to reject incoming traffic
sudo ufw default deny incoming
sudo ufw default allow outgoing

# allow specific connections
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

sudo ufw enable
