#!/usr/bin/env bash
# Bash script that configures an Ubuntu server:
# localhost address 127.0.0.2
# facebook.com address 8.8.8.8

cp /etc/hosts ~/hosts.new

echo "127.0.0.2		localhost" > /etc/hosts
echo "8.8.8.8 		facebook.com" >> /etc/hosts

cp -f /etc/hosts ~/hosts.new
